"""Write mcps/TOOL_REFERENCE.md: every UACC and SnareVec tool with its parameters.

Read from the servers' own source, not from memory, so a skill can be checked
against what the tools really accept. Costs nothing - no model is involved.

    python dev/toolref.py            write the reference
    python dev/toolref.py --audit    also check every tool and argument the skills name
"""
import ast
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
UACC = ROOT / "mcps" / "UACC" / "uacc_mcp" / "server.py"
SNARE = Path(r"C:\Users\adity\Desktop\blueeClaw\git\broswer extension\snarevec\pro\mcp\snarevec_mcp.py")


def uacc_tools():
    tree = ast.parse(UACC.read_text(encoding="utf-8"))
    out = {}
    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if not any("tool" in ast.unparse(d) for d in node.decorator_list):
            continue
        args = node.args
        defaults = [None] * (len(args.args) - len(args.defaults)) + list(args.defaults)
        params = []
        for a, d in zip(args.args, defaults):
            if a.arg in ("self", "ctx"):
                continue
            ann = ast.unparse(a.annotation) if a.annotation else ""
            params.append(a.arg + (f": {ann}" if ann else "") + ("" if d is None else f" = {ast.unparse(d)}"))
        doc = (ast.get_docstring(node) or "").strip().split("\n")[0]
        out[node.name] = (params, doc)
    return out


def snare_tools():
    # Import the module and read its TOOLS list: exact, where pattern-matching
    # the source silently dropped tools defined in a different style (it found
    # 28, then 25, of 31). The module is a stdlib-only proxy; importing it
    # starts nothing.
    sys.path.insert(0, str(SNARE.parent))
    import snarevec_mcp
    out = {}
    for t in snarevec_mcp.TOOLS:
        schema = t.get("inputSchema", {})
        req = set(schema.get("required", []))
        props = [p + ("*" if p in req else "") for p in schema.get("properties", {})]
        desc = " ".join(str(t.get("description", "")).split())
        out[t["name"]] = (props, desc.split(". ")[0])
    return out


def _unused_snare_tools_by_pattern():
    text = SNARE.read_text(encoding="utf-8")
    # The TOOLS list is a Python literal of dicts with name/description/inputSchema;
    # TAB_SCHEMA and friends are spread into it, so read names and property keys
    # by pattern rather than evaluating the module.
    out = {}
    # A description is either a parenthesised run of strings or one plain string;
    # matching only the first form silently dropped browser_new_tab and friends.
    for m in re.finditer(r'"name":\s*"([a-z_]+)",\s*"description":\s*(\(.*?\)|"(?:[^"\\]|\\.)*"),\s*"inputSchema":\s*(\{.*?\n        \})', text, re.S):
        name, desc, schema = m.group(1), m.group(2), m.group(3)
        desc = " ".join(re.findall(r'"((?:[^"\\]|\\.)*)"', desc))
        props = re.findall(r'"([a-z_]+)":\s*\{', schema.split('"properties"', 1)[-1])
        if "TAB_SCHEMA" in schema:
            props.append("tab_id")
        req = re.search(r'"required":\s*\[([^\]]*)\]', schema)
        required = re.findall(r'"([a-z_]+)"', req.group(1)) if req else []
        props = [p for p in dict.fromkeys(props) if p not in ("type", "items", "properties")]
        out[name] = ([p + ("*" if p in required else "") for p in props], desc.split(". ")[0])
    return out


def main():
    u, s = uacc_tools(), snare_tools()
    lines = [
        "# MCP tool reference - UACC and SnareVec",
        "",
        "Generated by `python dev/toolref.py` from each server's source. `*` = required.",
        "",
        f"## SnareVec ({len(s)} tools)", "",
        "| tool | parameters | what it does |", "|---|---|---|",
    ]
    lines += [f"| `snarevec__{n}` | {', '.join(p) or '-'} | {d} |" for n, (p, d) in sorted(s.items())]
    lines += ["", f"## UACC ({len(u)} tools)", "", "| tool | parameters | what it does |", "|---|---|---|"]
    lines += [f"| `uacc__{n}` | {', '.join(p) or '-'} | {d.replace('|', '/')} |" for n, (p, d) in sorted(u.items())]
    (ROOT / "mcps" / "TOOL_REFERENCE.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"snarevec {len(s)} tools, uacc {len(u)} tools -> mcps/TOOL_REFERENCE.md")

    if "--audit" in sys.argv:
        known = {f"snarevec__{n}": p for n, (p, _) in s.items()} | {f"uacc__{n}": p for n, (p, _) in u.items()}
        bad = 0
        for f in sorted((ROOT / "skills").rglob("*.md")):
            body = f.read_text(encoding="utf-8")
            for name in sorted(set(re.findall(r"\b((?:snarevec|uacc)__[a-z_]+)", body))):
                if name not in known:
                    print(f"  MISSING TOOL  {f.name}: {name}")
                    bad += 1
            # `tool` ... `arg: value` mentions in the same backticked span
            for tool, arg in re.findall(r"`((?:snarevec|uacc)__[a-z_]+)`[^`\n]{0,40}`([a-z_]+):", body):
                params = [p.split(":")[0].split(" ")[0].rstrip("*") for p in known.get(tool, [])]
                if tool in known and arg not in params:
                    print(f"  UNKNOWN ARG   {f.name}: {tool} has no `{arg}` (has: {', '.join(params)})")
                    bad += 1
        print(f"audit: {bad} problem(s)")


main()
